name: ign fortress test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run bootstrap
        run: ./bootstrap.sh

      - name: Check Gazebo Fortress Availability
        run: ./scripts/status_gazebo_fortress.sh
